#pragma once

#include <Core/Core.h>

namespace Vortex {

namespace Action {

	enum Constants
	{
		MAX_RECENT_FILES = 99,
		MAX_NOTESKINS = 99,
	};

	/// Enumeration of global actions that can be performed by the editor.
	enum Type {

	NONE,
	
	EXIT_PROGRAM,
	
	FILE_OPEN,
	FILE_SAVE,
	FILE_SAVE_AS,
	FILE_CLOSE,
	
	FILE_OPEN_RECENT_BEGIN,
	FILE_OPEN_RECENT_END = FILE_OPEN_RECENT_BEGIN + MAX_RECENT_FILES,

	FILE_CLEAR_RECENT_FILES,
	
	OPEN_DIALOG_SONG_PROPERTIES,
	OPEN_DIALOG_CHART_PROPERTIES,
	OPEN_DIALOG_CHART_LIST,
	OPEN_DIALOG_NEW_CHART,
	OPEN_DIALOG_ADJUST_SYNC,
	OPEN_DIALOG_ADJUST_TEMPO,
	OPEN_DIALOG_ADJUST_TEMPO_SM5,
	OPEN_DIALOG_DANCING_BOT,
	OPEN_DIALOG_GENERATE_NOTES,
	OPEN_DIALOG_TEMPO_BREAKDOWN,
	OPEN_DIALOG_WAVEFORM_SETTINGS,
	OPEN_DIALOG_ZOOM,
	
	EDIT_UNDO,
	EDIT_REDO,
	EDIT_CUT,
	EDIT_COPY,
	EDIT_PASTE,
	EDIT_DELETE,

	TOGGLE_JUMP_TO_NEXT_NOTE,
	TOGGLE_UNDO_REDO_JUMP,
	TOGGLE_TIME_BASED_COPY,
	
	SELECT_ALL,
	SELECT_REGION,
	SELECT_ALL_STEPS,
	SELECT_ALL_MINES,
	SELECT_ALL_HOLDS,
	SELECT_ALL_ROLLS,
	SELECT_REGION_BEFORE_CURSOR,
	SELECT_REGION_AFTER_CURSOR,

	SELECT_QUANT_4,
	SELECT_QUANT_8,
	SELECT_QUANT_12,
	SELECT_QUANT_16,
	SELECT_QUANT_24,
	SELECT_QUANT_32,
	SELECT_QUANT_48,
	SELECT_QUANT_64,
	SELECT_QUANT_192,
	
	CHART_PREVIOUS,
	CHART_NEXT,
	CHART_DELETE,

	SIMFILE_PREVIOUS,
	SIMFILE_NEXT,
	
	CHART_CONVERT_COUPLES_TO_ROUTINE,
	CHART_CONVERT_ROUTINE_TO_COUPLES,
	
	CHANGE_HOLDS_TO_STEPS,
	CHANGE_NOTES_TO_MINES,
	CHANGE_BETWEEN_HOLDS_AND_ROLLS,
	CHANGE_BETWEEN_PLAYER_NUMBERS,
	
	MIRROR_NOTES_VERTICALLY,
	MIRROR_NOTES_HORIZONTALLY,
	MIRROR_NOTES_FULL,

	EXPORT_NOTES_AS_LUA_TABLE,

	SCALE_NOTES_2_TO_1,
	SCALE_NOTES_3_TO_2,
	SCALE_NOTES_4_TO_3,
	SCALE_NOTES_1_TO_2,
	SCALE_NOTES_2_TO_3,
	SCALE_NOTES_3_TO_4,
	
	SWITCH_TO_SYNC_MODE,
	
	VOLUME_RESET,
	VOLUME_INCREASE,
	VOLUME_DECREASE,
	VOLUME_MUTE,
	
	CONVERT_MUSIC_TO_OGG,
	
	SPEED_RESET,
	SPEED_INCREASE,
	SPEED_DECREASE,
	
	TOGGLE_BEAT_TICK,
	TOGGLE_NOTE_TICK,
	
	TOGGLE_SHOW_WAVEFORM,
	TOGGLE_SHOW_BEAT_LINES,
	TOGGLE_SHOW_NOTES,
	TOGGLE_SHOW_TEMPO_BOXES,
	TOGGLE_SHOW_TEMPO_HELP,
	TOGGLE_REVERSE_SCROLL,
	TOGGLE_CHART_PREVIEW,

	MINIMAP_SET_NOTES,
	MINIMAP_SET_DENSITY,
	
	BACKGROUND_HIDE,
	BACKGROUND_INCREASE_ALPHA,
	BACKGROUND_DECREASE_ALPHA,
	BACKGROUND_SET_STRETCH,
	BACKGROUND_SET_LETTERBOX,
	BACKGROUND_SET_CROP,

	USE_TIME_BASED_VIEW,
	USE_ROW_BASED_VIEW,
	
	ZOOM_RESET,
	ZOOM_IN,
	ZOOM_OUT,
	SCALE_INCREASE,
	SCALE_DECREASE,

	SET_NOTESKIN_BEGIN,
	SET_NOTESKIN_END = SET_NOTESKIN_BEGIN + MAX_NOTESKINS,

	SNAP_RESET,
	SNAP_NEXT,
	SNAP_PREVIOUS,
	
	CURSOR_UP,
	CURSOR_DOWN,
	CURSOR_PREVIOUS_BEAT,
	CURSOR_NEXT_BEAT,
	CURSOR_PREVIOUS_MEASURE,
	CURSOR_NEXT_MEASURE,
	CURSOR_STREAM_START,
	CURSOR_STREAM_END,
	CURSOR_SELECTION_START,
	CURSOR_SELECTION_END,
	CURSOR_CHART_START,
	CURSOR_CHART_END,
	
	TOGGLE_STATUS_CHART,
	TOGGLE_STATUS_SNAP,
	TOGGLE_STATUS_BPM,
	TOGGLE_STATUS_ROW,
	TOGGLE_STATUS_BEAT,
	TOGGLE_STATUS_MEASURE,
	TOGGLE_STATUS_TIME,
	TOGGLE_STATUS_TIMING_MODE,
	
	SHOW_SHORTCUTS,
	SHOW_MESSAGE_LOG,
	SHOW_DEBUG_LOG,
	SHOW_ABOUT,
	SHOW_DONATE,

	};

	// Performs the action associated with the action type.
	void perform(Type action);
};

}; // namespace Vortex