name: Build & Latest Beta

on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  windows:
    name: "Build Windows x64"
    runs-on: windows-2022
    permissions:
      contents: read
    steps:
      - name: Get AV
        uses: actions/checkout@v4
      - name: Get MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Obtain oggenc2.exe
        run: >
          curl https://www.rarewares.org/files/ogg/oggenc2.88-1.3.7-x64.zip --output oggenc.zip &&
          unzip oggenc.zip -d .
        shell: bash
      - name: Build AV
        run: msbuild build\VisualStudio\ArrowVortex.vcxproj /p:Configuration=Release /p:Platform=x64         
      - name: Collect into a directory
        if: github.ref_name == 'beta'
        run: |
          mkdir AV
          cp -r bin/{assets,noteskins,settings} AV
          cp bin/ArrowVortex.exe oggenc2.exe AV
        shell: bash
      - name: Upload artifact
        if: github.ref_name == 'beta'
        uses: actions/upload-artifact@v4
        with:
          name: AV
          path: AV/
          if-no-files-found: error
