on:
  push:
  pull_request:
    branches:
      - beta
    paths-ignore:
      - '**.md'

name: Latest Beta

jobs:
  windows:
    name: "Build Windows x64"
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ${{github.workspace}}/main
    steps:
      - name: Get AV
        uses: actions/checkout@v4
        with:
          path: main
      - name: Get MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Obtain oggenc2.exe
        run: >
          curl https://www.rarewares.org/files/ogg/oggenc2.88-1.3.7-x64.zip --output oggenc.zip &&
          unzip oggenc.zip -d .
      - name: Configure CMake
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
      - name: Build AV
        run: cmake --build build --config Release
      - name: Collect into a directory
        run: |
          mkdir AV
          cmake --install build --config Release --prefix ./AV
          mv oggenc2.exe AV/bin
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AV
          path: main/AV/bin
          if-no-files-found: error
