name: Build & Latest Beta

on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  windows:
    name: "Build Windows x64"
    runs-on: windows-2022
    permissions:
      contents: read
    steps:
      - name: Get AV
        uses: actions/checkout@v4
      - name: Get MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Check formatting with clang-format
        run: >
          git ls-files "src/**/*.cpp" "src/**/*.h" | ForEach-Object {
              clang-format --dry-run --Werror --style=file $_
          }
      - name: Obtain oggenc2.exe
        run: >
          curl https://www.rarewares.org/files/ogg/oggenc2.88-1.3.7-x64.zip --output oggenc.zip &&
          unzip oggenc.zip -d bin/
        shell: bash
      - name: Build AV
        run: msbuild build\VisualStudio\ArrowVortex.vcxproj /p:Configuration=Release /p:Platform=x64         
      - name: Upload artifact
        if: github.ref_name == 'beta'
        uses: actions/upload-artifact@v4
        with:
          name: AV
          path: |
            bin/assets
            bin/noteskins
            bin/settings
            bin/ArrowVortex.exe
            bin/oggenc2.exe
          if-no-files-found: error
